### ISSUE TITLE
Select Wordpress template

### ISSUE THREAD

**Issue by dreashola** [dreashola/fractional-app#2]
- [x] Install Local
- [x] Install Astra template

**Comment by dreashola** [comment]
@deletosh Sorry for missing Saturday's meeting, I had an emergency that I couldn't avoid.
I'm having a challenge with the [How to Make a Website with Astra](https://www.youtube.com/watch?v=HSIb_VCS1Dc) video, the hosting and domain are paid options. How do I get past this?

**Comment by deletosh** [comment]
@dreashola For now, you can use it on Local. [Here is how](https://localwp.com/help-docs/getting-started/installing-local/). I will later share a hosted option with you

**Comment by dreashola** [comment]
Completed

**Comment by deletosh** [comment]
Nice!
